# -*- mode: org; mode: auto-fill -*-
#+TITLE: 辩证思维毁了我的羊杂汤
#+AUTHOR: KDr2

#+OPTIONS: toc:nil
#+OPTIONS: num:nil

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw

<2014-04-19 Sat>

“老板，来一份羊杂汤，打包！”

“好嘞, 没饭盒，拿袋子给您装一下？”

“行。”

不到十分钟，打包好的袋子就到了我的手中，我提着这一袋羊咋汤往回走，一路
上这袋子随着我的步伐荡来荡去，里面的蒸汽给胀起的袋子上方布了一层白白的
水珠，下方的羊杂也不肯默默的沉淀，拼着最后的力气向上翻腾。

忽然间，我迸出一个想法：我的大脑就像这袋羊杂汤，晃晃荡荡，毫无目的。这
个想法如此强烈，就像还在袋子里漂浮的那片毛肚，慢悠悠的翻来覆去，如此显
眼，如此清晰。

为什么会变得这样，我仔细回想，最后思维定位在了中学的作文课上。老师给我
们一系列议题，诸如“金钱是万恶之源”，“敢为天下先”之类，让我们写一篇大论
来支持一个从中提取的观点，这倒是不难，毕竟作文不是辩论会，没人跟你对着
打脸。但是，那段时间我们还在学习另一门众所周知的课程，里面就不停的强调
辩证思维，虽然这门课程我没有及格过，但是辩证思维这把如今人人都配备的利
剑还是深深的劈进了我的脑海里，我的心里，还好我不会唱歌。于是，我的议论
文完完全全的走了型，我开始支持一个观点，等我绞尽脑汁拼凑了750个字来支
持这个观点并且就要大获全胜的时候，我发现，这个观点不对！它不够辩证！但
是为时以晚，如同电影结尾前的大反派，我已经回不了头，尽管如此，我还是压
抑不住我那强烈的“我想做好人”的念头，走投无路的我开始打圆场，搬出对立观
点，絮叨几句，跟读者（也许应该是老师？）语重心长的说，你看我有我的论据，
它也有它的道理，这事儿你得辩证的看…… 结果可想而知，体育老师打人还是很
疼的！如此几次三番后我觉得这样不是办法，同时我还想坚持做好人，我就想了
一个绝对聪明的办法：在作文的一开头我就摆明，下面我将跟自己开一场双赢的
辩论会！尽管结果很不理想，但是它还是没能阻止我做一个好人。

从那时起，我追求的目标都有了它的另一面，一切都不再完美，于是我左右摇摆，
一路寻找新的目标，直到今日，仍无结局。

我还有哪些思维是不辩证的么？我苦苦思索，哦对！孔卡批评中国球迷不够铁，
而深处此境的我却毫不辩证的支持切尔西！

“哎哟，不好！”

也许是我想的太入神，提着羊杂汤的手竟然撞到了路边的垃圾桶上，看到地上的
羊杂汤渐渐流去，只剩两层湿乎乎的袋子裹着些黑乎乎的羊杂，我无比的惋惜，
终于，我定了定神，想：

我刚才想得对不对？有没有辨证的看待问题？

算了，我还是回去吃碗泡馍吧！

吃完回来路上看到几个人围在我撒的羊杂汤跟前讨论那是什么东西，有的人说那
是羊杂汤，有的说那绝对不是，嘿嘿，管他呢，我已经吃饱啦！


* Share This Page
  #+BEGIN: inc-file :file "sharethis.inc.org"
  #+END:

* Discuss and Comment
  #+BEGIN: inc-file :file "disqus.inc.org"
  #+END:
