# -*- mode: org; mode: auto-fill -*-
#+TITLE: Docker issues I met
#+AUTHOR: KDr2

# #+OPTIONS: toc:nil
# #+OPTIONS: num:nil

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw
#+CALL: meta-keywords(kws='("docker" "issue" "lxc" "container" "virtulization")) :results raw

# - DATE
<2014-07-15 Tue>


#+BEGIN: inc-file :file "flattr.inc.org"
#+END:

I started to use docker in the past few days, and encountered few issues:

# - CONTENT
* Use docker as a non-root user without ~sudo~
  I am using debian and installed docker with ~aptitude~, that created
  a new group named ~docker~, and the unix socket file created by the
  docker daemon is owned by that group:

  #+BEGIN_EXAMPLE
  $ ls /run/docker.sock -l
  srw-rw---- 1 root docker 0 Jul 14 20:46 /run/docker.sock
  #+END_EXAMPLE

  so just add the user you are using to the group ~docker~,  then you
  can easily use docker command without ~sudo~:
  #+BEGIN_SRC sh
  $usermod -a -G docker
  $newgrp docker # this command make the previous command take effect without logging out/in
  #+END_SRC

  You can use ~-G~ option of docker daemon to specify a group rather
  than using the default ~docker~ group.

* Generate layer archive error
  When I pushed a docker image to docker hub, it issues:

  #+BEGIN_EXAMPLE
  2014/07/14 09:14:15 Failed to generate layer archive: Error activating devmapper device for '062d727961a00bf89f725160b52af9eb22ec23ba7826172b5333351876e26ef4':
  Error running DeviceCreate (activateDevice) dm_task_run failed
  #+END_EXAMPLE

  Restart the daemon and do it again!

* Hang while pushing images
  Shit, *docker hub is banned in China*, so use a VPN or a proxy please,
  I circumvent this by running docker daemon with =tsocks=:
  #+BEGIN_SRC sh
  $sudo tsocks /etc/init.d/docker.io restart
  #+END_SRC

* Error: push repository is already in progress
  You must killed a hung pushing process :), just restart the docker
  daemon and push again.

* Other Errors
  *Just restart the daemon and do it again!* It will solve most problems!

#+BEGIN: inc-file :file "gad.inc.org"
#+END:


* Discuss and Comment
  #+BEGIN: inc-file :file "disqus.inc.org"
  #+END:
