# -*- mode: org; mode: auto-fill -*-
#+TITLE: A Docker Image for Moochine Demo
#+AUTHOR: KDr2

# #+OPTIONS: toc:nil
# #+OPTIONS: num:nil

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw
#+CALL: meta-keywords(kws='("docker" "nginx" "openresty" "moochine" "demo")) :results raw

# - DATE
<2014-08-10 Sun>


* Moochine and Moochine-Demo
  [[file:../../project/moochine.org][Moochine]] is a simple web framework based on Openresty I created. And
  moochine-demo(https://github.com/appwilldev/moochine-demo) is a
  simple moochine app to demonstrate how to use the framework. You can
  also use it as a scratch to start your own moochine app. For the
  newbies, it seems terrible to setup such a complicated environment,
  eventually it's not. Anyhow, I created a Docker image with that demo
  running on for them.

* The Docker Image

  The image is taged with "sid-moochine" on
  https://registry.hub.docker.com/u/kdr2/debian/, you can get it
  easily:

  #+BEGIN_SRC sh
  docker pull kdr2/debian:sid-moochine
  #+END_SRC

  And then start the demo:

  #+BEGIN_SRC sh
  docker run -d -p 0.0.0.0:9801:9800 kdr2/debian:sid-moochine /root/moochine-demo/bin/start.sh -f
  #+END_SRC

  The option ~-f~ for ~start.sh~ tells Nginx(openresty) to run at
  foregroud, so the Docker container will be running on. We also map
  the port with option ~-p 0.0.0.0:9801:9800~ for Docker, so you can
  visit http://localhost:9801/ltp on the host OS to see if your demo
  is running well.

  But, there's no database(redis, pgsql, mysql) installed in this
  image, you should install them yourself if you want to use
  them. It's simple:
  - run the image and start a shell:
    #+BEGIN_SRC sh
    $ docker run -t -i -p 0.0.0.0:9801:9800 kdr2/debian:sid-moochine /bin/bash
    #+END_SRC
  - install what you want (using ~aptitude~) and start them in that shell;
  - start the demo:
    #+BEGIN_SRC sh
    root@4df89d75e286:/# /root/moochine-demo/bin/start.sh
    #+END_SRC


  You can also let the demo connect the database on your host OS: just
  change their server address in the code.

#+BEGIN: inc-file :file "gad.inc.org"
#+END:


* Discuss and Comment
  #+BEGIN: inc-file :file "disqus.inc.org"
  #+END:
