# -*- mode: org; mode: auto-fill -*-
#+TITLE: An Indistinct Mind
#+AUTHOR: KDr2
#+OPTIONS: num:nil
#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw

Simple, tough, resilient, optimistic, that's me. I'm KDr2 (Killian
Q. Zhuo), a nostalgist in technology, a martinet in behavior, a
misanthrope in society, an ascetic in spirit, a logical positivist in
philosophy, a learner in lifetime.

I live with my kid and we two together lead a simple life.

I am searching for a better understanding of myself and my
surroundings. To achieve so, I dedicate my thoughts to epistemology,
cognitive science, computer science, and linguistics. I read, think,
practice, and write. I would like to write here about things I
learned, if I think they are worth writing. But getting such things is
hard to me, a person on the hard way. So please don't set any
expectation.

* Navigation
- [[file:project/index.org][Projects]] / [[file:misc/books.org][Books]]
- [[file:misc/categories.org][Categories]] / [[file:misc/archives.org][Archives]]
- [[file:misc/site-log.org][Changelog]] / [[http://kdr2.com/misc/site-log.xml][RSS]]
- [[file:misc/about-josh.org][About Josh]]

* Recent Posts
#+NAME: recent-posts
#+BEGIN_SRC elisp :exports none :results raw value
  (make-recent-posts 10 t)
#+END_SRC
#+CALL: recent-posts[:results value]() :results raw
