# -*- mode: org; mode: auto-fill -*-
#+TITLE: An Indistinct Mind
#+AUTHOR: KDr2
#+OPTIONS: num:nil
#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw

# #+ATTR_HTML: :alt R2D2 :title R2D2 :align right


Hi, I'm KDr2(ZHUO QL), a nostalgist in technology, a martinet in
behavior, a misanthrope in society, an ascetic in spirit, a learner in
the lifetime.

I am searching for a better understanding of myself and my
surroundings. To achieve so, I dedicate my thoughts to epistemology,
cognitive science, computer science, and linguistics. I read, think,
practice, and write. I would like to write here about things I
learned, if I think they are worth to write. But getting such things
is hard to me, a person on the hard way. So please don't set any
expectation.

* Navigation
- [[https://www.notion.so/What-is-happening-3fa589c95cb8497fb9a70fec96675db1][What's happening]]
- [[file:project/index.org][Projects]] / [[file:misc/books.org][Books]] / [[file:resource/index.org][Resources]]
- [[file:misc/categories.org][Categories]] / [[file:misc/archives.org][Archives]]
- [[file:misc/site-log.org][Changelog]] / [[http://kdr2.com/misc/site-log.xml][RSS]]
* Recent Posts
  #+NAME: recent-posts
  #+BEGIN_SRC elisp :exports none :results raw value
    (make-recent-posts 10 t)
  #+END_SRC
  #+CALL: recent-posts[:results value]() :results raw
