# -*- mode: org; mode: auto-fill; -*-
#+TITLE: About me and this site
#+AUTHOR: KDr2

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw
#+CALL: meta-keywords(kws='("KDr2" "free lancer")) :results raw

* About Me

  Hi, I'm KDr2(ZHUO Qingliang), a nostalgist in technology, a martinet
  in behavior, a misanthrope in society, an ascetic in spirit, a
  logical positivist in philosophy, a learner in lifetime, and more:

  - An old-fashioned hardcore Linux guy
  - An open-source supporter, NOT an opponent of GPL
  - An Emacs and Orgmode user
  - A reader, and a writer
  - An idiot of music and rhythm

  #+BEGIN_EXPORT HTML
  <!--

  /---------------------------------------------\
  | Want more info about me? here is my resume: |
  | https://kdr2.com/misc/resume.html            |
  \---------------------------------------------/
          .-.
         /_ _\
         |o^o|
         \ _ /
        .-'-'-.
      /`)  .  (`\
     / /|.-'-.|\ \
     \ \| (_) |/ /  .-""-.
      \_\'-.-'/_/  /[] _ _\
      /_/ \_/ \_\ _|_o_LII|_
        |'._.'|  / | ==== | \
        |  |  |  |_| ==== |_|
         \_|_/    ||" ||  ||
         |-|-|    ||LI  o ||
         |_|_|    ||'----'||
        /_/ \_\  /__|    |__\

  -->
  #+END_EXPORT

** Contact Me
   :PROPERTIES:
   :CUSTOM_ID: contact_me
   :END:
   - Location: Xi'an, Shaanxi, China
   - Skype : zhuoql
   - Emails :
     - zhuo@@html:&#x01F4E7;@@hexoasis.com,
       zhuoql@@html:&#x01F4E7;@@zoho.com, for personal affairs.
     - zhuoql@@html:&#x01F4E7;@@yahoo.com, for development affairs,
       e.g. mail list, bug report.
   - Mobile : +86 0b10111010 05532 0x0636

#+BEGIN: inc-file :file "gad.inc.org"
#+END:

* About This Site
  This site is built with emacs and orgmode, hosted on [[http://www.dreamhost.com/r.cgi?377047][DreamHost]].

  You can find my org mode configuration at
  https://github.com/KDr2/emacs.d/blob/master/src/elisp/tools/init-org.el
  and https://github.com/KDr2/kdr2-on-web/blob/master/script/.  The
  source repository of this site is hosted on [[https://github.com/KDr2/kdr2-on-web][GitHub]].

  I write here things that I think are worth to read, and hope they
  help. Feel free to contact me if you want.

* Discuss and Comment
#+INCLUDE: ../include/comment.inc.org
