# -*- mode: org; mode: auto-fill; -*-
#+TITLE: About me and this site
#+AUTHOR: KDr2

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw
#+CALL: meta-keywords(kws='("KDr2" "freelancer")) :results raw

* About Me
  Hi, I'm KDr2(Killian Zhuo), a nostalgist in technology, a martinet
  in behavior, a misanthrope in society, an ascetic in spirit, a
  logical positivist in philosophy, a learner in lifetime.

  I am interested in many domains including:

  - Computer science and programming
  - Cognitive Science
  - Reading and writing
  - Child Education
  - Data science
  - Finance

  #+BEGIN_EXPORT HTML
  <!-- -----------------------------------------\
  | Want more info about me? here is my resume: |
  | https://kdr2.com/misc/resume.html           |
  \------------------------------------------ -->
  #+END_EXPORT
** Contact Me
   :PROPERTIES:
   :CUSTOM_ID: contact_me
   :END:
   - Location: Xi'an, Shaanxi, China.
   - Email: killian.zhuo@@html:&#x01F4E7;@@gmail.com, or
     zhuo.dev@@html:&#x01F4E7;@@gmail.com.
   - Mobile: +86 0b10111010 0o5532 0x0636
   - [[file:resume.org][Resume]]
#+BEGIN: inc-file :file "gad.inc.org"
#+END:
* About This Site
  This site is built with emacs and orgmode, hosted on [[http://www.dreamhost.com/r.cgi?377047][DreamHost]].

  You can find my org mode configuration [[https://github.com/KDr2/emacs.d/blob/master/src/elisp/tools/init-org.el][here]] and the build scripts
  for this site [[https://github.com/KDr2/kdr2-on-web/blob/master/script/][here]].  The source repository of this site is hosted on
  [[https://github.com/KDr2/kdr2-on-web][GitHub]].

  I write here things that I think are worth reading, and hope they
  help. Feel free to contact me if you want.

  Thers's also [[file:about-josh.org][an about page of my boy]] on this site.
* Discuss and Comment
#+INCLUDE: ../include/comment.inc.org
