#!/bin/bash
# -*- sh -*-

BASENAME=`dirname $0`/..
mkdir -p $BASENAME/depot/images/

# upload
rsync -avr $BASENAME/depot/images/ kdr2@kdr2.com:depot/img-kdr2-com/

# download
rsync -avr kdr2@kdr2.com:depot/img-kdr2-com/ $BASENAME/depot/images/

# upload to cloudinary
python $BASENAME/script/upload-images-to-cloudinary.py
