# -*- mode: org; mode: auto-fill -*-
#+TITLE: 仔句精选, 2017
#+AUTHOR: KDr2

#+OPTIONS: toc:nil
#+OPTIONS: num:nil

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw

#+BEGIN: inc-file :file "gad.inc.org"
#+END:

# - DATE
<2018-02-25 Sun>

# 仔句精选

仔两岁前表达基本靠手和“嗯嗯”，刚过两岁就开始不停的说，在发生下面“三千
句”的对话后，开始随手记录有意思的语句，本页是2017年记录的汇总。

* 20170308
** 三千句
  我家仔现在特别能说，一天从早到晚说不停，最喜欢电梯。

  媳妇：现在仔每天至少要说三千句… \\
  我：仔这是在为父报仇！ \\
  媳妇：… \\
  仔：爸爸（上班的地方）有一个观光（电梯）不上也不下（停运）…

* 20170309
** 立体感
   打开相邻的两层抽屉说：“上面一层下面一层，更有立体感”。
** 吼猴
   学会了一个简短冷笑话：“有一种猴叫吼猴”，然后不停给自己讲自己乐。

* 20170311
** 发出啊啊的声音
   自己“啊～啊～”叫两声，然后慢悠悠的说：“发出啊啊的声音…”
** 长句
   下面两句话，都是一口气憋着说完的，脸都快红了：
    - 爸爸有一个小观光不上不下没人坐还有四个不观光能上能下有人坐仔仔按
      过开门关门能控制…
    - 外面（某商场）有两个观光有时候叮（电梯到达的提示音）有时候不叮还
      有三个观光（不同地方两组观光电梯）也是有时候叮有时候不叮…

      注：现在区分电梯靠观光不观光，区分笔靠画出的颜色荧光不荧光…
** 刷卡搞定一切
   手持我的过期信用卡，骑在小车上，边溜边喊：“刷卡，刷爸爸卡，刷卡搞定
   一切！”

   前两句是妈妈教的，最后一句到现在还没搞明白从哪学的…
* 20170312
** 拼命！
   养乐多限定每天一个，今天跟妈妈谈判：

   仔：“喝完，重新拿一个！” \\
   妈：“今天的额度用完了，明天再喝。” \\
   仔坚持：”重新拿一个重新拿一个” \\
   妈：“#^*+#%～，不能拼命喝” \\
   仔：“拼命！拼命！” \\
   几个回合下来妈松口：“去找爸爸给你打开” \\
   仔举着养乐多朝我跑来：“找爸爸拼命！找爸爸拼命！” \\
   我：“…”

** 同义词近义词的排列组合

   跑到卧室外关门喊“把爸爸关住”，一会儿又打开说“把爸爸开住”…

   特别喜欢自己琢磨同义词近义词的排列组合，过往的有：开始—关始，我赶紧
   教“没有关始，只有关闭”，他自己把这八个字复习了五分钟，记住了。

   比较有意思的有，给他吃草莓的时候他自己嘀咕：“草莓，没？有？草有？草
   莓，草有！” 。

   最发指的出场：“妈咪，爸比，爸咪，M.B.”…还没法纠正，只好装没听见，自
   己说了一周，终于淡忘了。

* 20170313
  今天急性胃炎了，但还是特别乖，一点也没闹。
** 没声音
   大家一起坐沙发玩呢，他突然放了一个响P，我们还没说啥，他自己抢着说：
   “没声音～～”

* 20170316
** 白瓜里面不白瓜
   肠胃炎刚好，看啥都想吃，但是啥都是吃一口就跑了。晚饭黄瓜（我们黄瓜
   都去皮吃，他坚持称黄瓜是白瓜，每一次说黄瓜他都要纠正）拌了素鸡，他
   喜欢吃这个豆制品，想要我们给他喂但是不会说，憋了半天说道：“白瓜里面
   不白瓜！” …

* 20170402
** 两个黄鹂
   对着图教仔两个黄鹂鸣翠柳，开始仔说两个鸟鸟……，教到后来，仔说：

   *两个黄鹂变红鹂！*

   是不是带仔看球看多了……

* 20170403
** 施工
   玩塔吊呢，跟我说这次又没成功，我趁机扩充他词汇说，你也可以说这次失
   败了，一个意思能省一个字。一会儿他跟我说：“这次又失功！”呃…你说你又
   在施工🚧倒也没错…
** 大意了
   玩的时候没玩好会说 “不小心” 或 “这次又不小心”，今天一次玩手机点歪了，
   说：“这次没有不小心，（这次）大意了！”… 不靠谱程度丝毫不逊于我。
* 20170421
** 植物
   媳妇给仔画了一棵树，说，来，今天我们来学植物相关知识，刚讲出根、茎、
   叶，仔说：不学不学，要学弯物，弯物弯物！后来我趁机讲了裸子植物和被
   子植物，他好像没太明白…
** 隐喻
   我经常用一些不着调的典故隐喻，比如仔一岁时，常试图同时弄好几件事，
   弄不成就着急，我就跟他说：仔，要一件一件来，先诛少林再灭武当，一起
   来你打不过的…他好像不懂。

   今天我吃东西呢他说他也要吃，我让他过来，他脸贴沙发蹭着慢慢向我蠕动，
    我说，儒尼尼奥，快变夸雷斯马！这次竟然领会了，不知道是不是里面有个
    快字被接收了…

* 20170423
** 豆腐块
   “要吃豆腐慢，要吃豆腐慢！” — 我想了一下才明白说的是豆腐块。
** 金箍棒
   自己会编小故事场景玩：悟空要进他的门，说猴猴用这个棍子敲敲门，然后
   朝我说：“爸爸讲这个棍子”，我说那是金箍棒，他说“是远箍棒！”，我赶紧
   给他解释虽然大禹神铁确实比较远古，但是“金”说的是它两端的颜色，不是
   远近的近，你要不同意可以说银箍棒红箍棒蓝箍棒甚至花箍棒，但是远箍棒
   说的可不是颜色，最后总算是把他说服了。
** 好朋友
   又在自己跟玩具玩偶玩，我跟他说，仔，给你出个难题，这只公鸡和这只狐
   狸都是你的好朋友，但是狐狸要吃公鸡（他看过的小羊肖恩里的剧情），你
   怎么办？说完我觉得这个题太难了……没想到仔说，“狐狸啊呜一口，没吃到公
   鸡，吃到别的…” 然后摸摸狐狸嘴说：“把狐狸嘴关上”。两岁的语言，也能解
   决难题了😊

* 20170429
** “耍死狗”专题
   最初是仔妈对我说，你看他一会儿，我去耍会儿死狗休息下，就去躺着了。
   几次之后仔就学会了“耍死狗”这个词，并会在妈妈耍死狗的时候要求一起去
   耍：爬到床上往床头一靠，头稍后仰也靠上，作葛优躺状，但是往往耍不过
   三秒旋即爬起来，或指正妈妈耍的姿势不标准位置不正确，或干脆就扑到妈
   妈那里蹭一阵子，才又回去耍几秒。

   我见是这样，就批评道：你这是“死狗当活狗耍”啊！仔妈大笑，他虽不懂也
   跟着笑并记住了这句话。之后每次耍死狗都叫上我，理由是“爸爸耍的好！”。
   我表示不明白，问他我耍的怎么好了，也没有把一条死狗耍的虎虎生风吧？
   然后他又学会了“虎虎生风”这个词，并且做了扩展，说耍死狗要“汪汪生风”…
   接下来还让很多拟声词都生了一阵子风这个词的热度才逐渐退去，也许他就
   是觉得耍死狗的同时能逗乐能学新东西才是耍的好吧，哈哈。

   最近开始在路上跟小动物打招呼，见了小喵，停下甚至蹲下，对着小猫喵一
   声，小猫回喵了他能高兴一整天；大唐西市古玩街上有一排鹩哥，其中一些
   能说“你好，再见，恭喜发财”等词，他每次过去也都会去跟这些鸟儿说上几
   句，“你好，再见，叽叽喳喳”都来几遍；有次在小区步行街上见到一只小小
   狗，他认真的朝狗汪汪打招呼，狗没理他走了，他郁闷的问妈妈：“仔仔汪汪
   小狗不汪汪是怎么回事？”…这句很快就出现在了耍死狗场景：前几天他又招
   呼大家去耍死狗，他耍好姿势后，呆了一会说：“全家汪汪死狗不汪汪是怎么
   回事？”…你说清楚啥时候全家汪汪的？！

* 20170516
** 一只懒猫，有啥可怕，壮起鼠胆，把猫打翻！

   自从学会了这个句子，便有了绝招，无论看到想到什么都可以把它推到“猫”
   的位置上，然后壮其鼠胆斗翻它，一招鲜，吃遍天：

   - 一个瓜子有啥可怕壮起鼠胆把瓜子啃翻~
   - 一只甲龙有啥可怕壮起鼠胆把甲龙打翻~
   - 一只吼猴有啥可怕壮起鼠胆把吼猴打翻~
   - ……

** 两个黄鹂鸣翠柳，一行白鹭上青天。

   这句学会以后，不两黄变一红了，开始直接给里面的动物变色：

   两个（红/绿）鹂鸣翠柳，一行（红/绿）鹭上青天。

   我随口说，你试试把颜色换成材质，比如，一行铁路上青天，那就是青藏高
   原！然后接下来大半个晚上他就不停念：两个铁鹂鸣翠柳，一行铁路上青天…
   🤐

* 20170523
  妈妈见闻杂记
** 带狮子去看木瓜

   最初听了《咕咚来了》只学会一句“没命跑”。前几天拿着山狮模型在地上爬，
   边爬边念念有词：“带狮子去看木瓜。”今天坐在飘窗上自己数：“一个木瓜掉
   水里，一个木瓜在树上。”

** 恭喜发财

   喜欢大唐西市古玩街上店家养的鹩哥，每次去都要和鹩哥说话，被鹩哥教会
   了：“你好！拜拜！恭喜发财！”

** 从“十万个是什么”向“十万个为什么”进化

   一天。“妈妈这是什么？”“山楂片。”“这是什么山楂片？”“这就是普通的山楂
   片。”“这是什么普通的山楂片？”“( ･᷄ὢ･᷅ ) 妈妈也说不上来了啊，这就是最
   普通的山楂片啊。”过了几天爸爸带去买山楂片，告诉爸爸：“这是妈妈也不
   知道的普通的山楂片。”

   _(:_」∠)_

** 放的下花花世界

   不喜欢睡觉。再困也要咬牙坚持不睡。劝睡就嗷嗷抗议。爸爸：“哎，仔仔还
   是放不下这个花花世界。”仔仔：“放下的。”（娃发音不准，句尾“了”总读作
   “的”）

   谁说完“放下的”又用脸蹭一阵沙发坐垫然后强打起精神继续玩的啊？！

* 20170526
** 不是拉屎的那个“完”

   之前一直跟仔强调，便便完了要跟我们说一声，让我们及时给你处理，一段
   时间后终于会说 “完了”或者 “拉完了”。同时期，吃饭时感觉他吃得差不多
   了，我习惯问他“吃饱了么？”。

   今天喂完饭，我没按常理，问了句“吃完了么？” 他答 “完了。”

   过了几秒后又补充：“不是拉屎的那个‘完’。”

   ……

* 20170604
  妈妈见闻杂记
** 一
   《咕咚来了》还在继续发酵。小家伙会忽然自己走到阳台上叨念：“楼下有棵
   木瓜树。树上有一个木瓜掉进湖里了。又长出三个木瓜。”有时候阳台门关着
   就会叨念：“看不到木瓜树的。”

** 二
   有一天我再次在他困而不肯睡的时候吐槽他放不下花花世界，他很认真地说：
   “放下了一点点。”紧接着补充，“大部分还是要去外面的。”

** 三
   绘本中的角色多是小动物，听多了看多了便喜欢自称是某个动物，还给家里
   人分配角色。

   最喜欢当蜜蜂，还有自己专有的贴满贴纸的小蜜罐（绘本里蜜蜂会背着一个
   小罐子去采花蜜）。我问他：“小蜜蜂你会采蜜吗？”他就会很认真地回答：
   “还不会。长大的就会的。”

   他对动物理解得很好。当蜜蜂的时候就拿着小蜜罐嗡嗡嗡；当小公鸡就喔喔
   喔把躺着的都喊起来；当小乌龟就呜呜呜哭着找不到乌龟妈妈/乌龟爸爸/乌
   龟姥姥（他的绘本里有小乌龟迷路）；当小猫头鹰就呜呜呜但不说原因
   （《爱哭的猫头鹰》里小猫头鹰就没理由地哭）；当小蜥蜴就走路一摇一摆
   念着“甩着尾巴走”。有阵子特别困整个蜷起来就说自己是小虾，会对妈妈说
   “虾妈妈抱小虾”。但在和妈妈一起读过儿童百科全书、知道小虾（明虾）非
   常小而龙虾比较大之后就改称自己为龙虾。如果妈妈叫他“小龙虾”，他就会
   挺起胸脯说：“已经是大龙虾的。”

** 四
   周末中午爸爸躺在卧室床上补觉。原本在客厅玩的他忽然杀了进去：“蜜蜂也
   要睡觉！睡爸爸那儿！”然后就扑过去搬动爸爸的头，拉开之后又扑过去扯爸
   爸脚，还“把爸爸的眼镜丢一边”。我把他从卧室抱出来要他不要打搅爸爸，
   他委屈地哭了，带着泪迷迷糊糊挂我肩上睡了过去。我把他轻轻放在爸爸身
   边，他睡得很安稳。我仔细想了想，忽然明白了他为什么那么做：他和我们
   一同睡大床，睡得早却不老实，总是满床乱滚，我和爸爸要睡的时候总要先
   把他搬回他自己的小褥子上。偶尔搬动时他会睁眼看我们一下随即又睡去。
   或许正是如此让他觉得一个人要睡觉了如果床上有别人就要把床上另一个人
   搬走并睡在他那里…… 崽儿，你对这个世界似乎有一些误会……( ･᷄ὢ･᷅ )

* 20170617
** 颗粒归仓

   之前教仔 “沧浪浪宝刀出鞘，哗啦啦马踏连营”，他只学会了第一句，并会变
   化着用：自己出场说“沧浪浪宝仔出鞘”，妈妈来了喊“沧浪浪宝妈出鞘”。

   还教过他“颗粒归仓”这个词语，他只知道跟粮食有关，吃饭的时候会说，但
   不太懂，后来他觉得“颗粒”可能是拟声词，就说克哩哩…可能跟《春天在哪里》
   有关。

   最近憋了个大招，把这些串起来了：

   *克哩哩哩哩…归…沧浪浪浪浪…!*

** 再探

   出去玩了一天，傍晚回到家休息，正耍死狗呢，他说：“爸爸，抱！”，我有
   点累不想抱，就随口说：“再探！”

   仔愣了一下，就换话题了，哈哈。

* 20170626
** 冰箱前的对话

   定好了规则每天只能给仔吃一块巧克力，今天的份额已用掉，但他还是想吃，
   于是让我抱他到冰箱前打开门，开始了如下对话：


   - 仔盯了巧克力盒子三秒，说：到明天了。
   - 我：没到呢，要睡了觉然后醒过来才算到了。
   - 仔瞪大眼睛：醒了。
   - 我：但是你还没睡呢，一直醒着不算。
   - 仔转身趴我肩上装作睡着，三秒后转过来：到周末了！
   - 我：…我也想这么快到周末！

   通篇对话都没出现“巧克力”三个字 👍🏻

* 20170715
** 回答问题的艺术

   一直以来都是我负责给仔洗澡，他不喜欢洗头，每次洗头时都要讲一些其他
   话题或故事来转移注意力，上周六晚上洗澡时，到洗头环节了，我想起他酷
   爱电梯，白天时又一天带他去了两个商场坐电梯，就问他：“今天是不是去中
   大国际和大唐西市了？中大国际的观光好还是大唐西市的观光好？”

   仔皱着眉头想了一会儿说：“ *今天还没去赛格呢！* ”

* 20170726
** 死心眼
   商场观光电梯一般并排好几个，仔去坐的时候要事先确定一个（好像是按顺
   序的），其他的来了也不上，还对着这个来了的电梯挥手喊拜拜，意思是你
   快走… 有次终于等来了他确定好的那个，我说：“功夫不负死心眼，快上去吧！”

   仔就记住了，有天晚上回到家里，忽然说：“仔仔有好多个死心眼，爸爸有一
   个死心眼！”

   仔妈赶紧抢着说：“对！”

* 20170727
** 这是啥人

   仔还不太会用代词，疑问代词也不太会，就用“啥人”代替“谁”，问“这是谁？”就
   说“这是啥人？”

   有天早上还没起床迷迷糊糊的往我怀里钻，钻了会儿伸出小手在我胸脯上找
   了一阵子，一脸疑惑和嫌弃的问：“这是啥人？”

   我说，是爸爸。他就去找妈妈了……

* 20170819
** 自知

   “大梦谁先觉？平生我自知。草堂春睡足，窗外日迟迟。”

   早上给仔反复教了几遍之后，仔对我的人生发出了严厉的拷问：

   “大梦谁先觉？平生你自知，你我都自知！一会儿自知一会儿不自知！”

* 20170905
** 举头望乌云
   最近持续下雨，跟仔背诵讲解《静夜思》的时候，仔说：我抬头看看天上的
   乌云，低下头，忽然有点想家了，我按了下16楼！

   对电梯的爱一如既往。

** 在书店

   我：“北风卷地白草折” 和 “线性代数”，想学哪个? \\
   仔："都想学。"

   于是买了 《唐诗三百首鉴赏辞典》（ISBN：9787532620487） 和 《同济大
   学数学系列教材 线性代数》（ISBN：9787115422750）。

   然后持续送武判官，之前学了《使至塞上》，我还为此专门查了下 “萧关逢
   候骑，都护在燕然” 和 “都护铁衣冷难着” 中的都护是不是同一个地方的都
   护甚至是不是同一个人，结果仔的关注点完全不同： “北风卷地白草蛇， 我
   就是那条小蛇。”，再后来白草蛇绿草蛇等五颜六色的草蛇都爬出来了……解释
   了好几次还是喜欢小蛇……难道要开始教 Python 🐍 嘛？我还想从 Perl6 🦋
   开始呢！



* 20171013
** 妈妈变黑了

   媳妇：……%&%…… 我都崩溃了。 \\
   仔：妈妈变黑了。 \\
   我：？？？ \\
   仔：妈妈崩溃了，妈妈变黑了。 \\
   我仔细想了一下，“崩溃”一词是仔玩手机的时候学会的，App 崩溃了，手机要黑屏一下……


** 下一句是什么

   教背诗，我和仔常互相问“下一句是什么？” \\
   一次晚饭，仔吃着吃着就要喝饮料，给喝了一些还不够，还要喝。 \\
   我随口说：仔，‘稀汤灌大肚’ 的养殖方法是错误的！ \\
   仔说：“下一句是什么？” \\
   额……我没想好下句呢，“干粮塑肥臀” 你看行么？
* 20171101
** 往日的平静
   国庆假后哄睡就从来没找过，每次睡前仔妈都要让仔选自己的 *哄睡人* ，
   仔回答：“选妈妈，爸爸是 *备用人* ……”

   今天威逼利诱成功了，终于选了爸爸做 *哄睡人* ，妈妈成了 *备用人* ，
   结果他在我旁边折腾够了后，把脸凑过来贴我脸上，说： *仔仔跟爸爸睡到
   了一起，爸爸又恢复了往日的平静。*

   我听完愣是憋住没动没笑，仔不到两分钟就睡着了……

* 20171212
** 诱导公式口诀
   昨晚哄睡，还是舍不得花花世界。

   仔：奇变偶不变! \\
   我：符号看象限! \\
   仔（高兴）：你们（咱们）俩在聊天呢！然后呢？\\
   我：聊着聊着就睡着了…… \\
   仔（生气，带哭腔）：才不要这样说呢！ \\
   然后一边玩去了……

* 20171223
** 着实小仔仔之就医记录（来自仔妈）

   自来暖气前一天断断续续病了一个月，实在扛不住带去了儿童医院就医。小
   崽经历了人生第一次雾化以及人生第一次挂水。

   1. 爸爸心疼崽在路上奔波，怕崽再着凉，试图说服崽在家里雾化。我出面充
      当说客：“宝宝，你想在家做雾化还是去医院做雾化？”崽：“要去医院做
      雾化。”爸爸急了，使出诱惑战术：“在家做雾化也能玩手机！”崽：“要去
      医院玩手机。”爸爸败。
   2. 口腔涂药和检查喉咙都需要张大嘴巴，崽已经养成了坐在医生或者护士面
      前就“啊”张嘴。耳鼻喉科经常会见到各种以前崽完全没见过的疾病与治疗
      手段，他总会目不转睛地看，然后小声说：“我有点紧张。”得到安慰之后
      就会放心地继续看，直到轮到自己去做治疗。
   3. 第一次挂水。抱崽去扎针之前我跟崽说：“一会儿要挂水了，扎针会疼。”
      崽：“有点紧张。”我说：“不用太紧张。扎针会疼，但也没有那么疼。就
      像你昨天抽血，针扎进去的时候会疼，但也没有那么疼一样的。”崽若有
      所思。扎针的时候，我本来想把崽在就诊台上放平，以为他没到3岁需要
      扎额头，结果护士说：“我们来看看能不能扎手吧。”我就说：“哎呀，宝
      宝是大孩子了，不扎头，要扎手了。”扎针的时候，崽没有缩，也没有哭，
      看着针头扎进去，然后下了地，自己走出了扎针专用的房间。那一瞬间，
      我有点想哭。
   4. 清洗鼻腔、口腔涂药、雾化吸入、输液扎针，这小家伙没有掉过一滴眼泪。
      但是回家了嘛……就一副小霸王的模样了，稍有点不顺着他的心意就一哭二
      闹。我跟姥姥说：“咱们收拾收拾搬医院去吧，崽在那里特别乖，比在家
      乖多了。”惹得姥姥一阵笑话我。
   5. 随着治疗的进行，崽逐渐恢复了健康，也恢复了食欲，每次雾化治疗之后
      的一碗水果是必不可少的。近期最爱草莓，每次去医院要带一碗，返程途
      中吃。今天最后一次雾化，爸爸给突然有点虚的我买了一个肉夹馍，崽看
      见了就立刻张嘴“啊——”要吃。但口腔涂药了，半小时不能吃喝，崽就各种
      不满意。爸爸出马：“回家路上吃，先吃草莓，再吃夹馍；草莓就夹馍；
      草莓夹馍。”崽：“不，脑子里只有夹馍。”我就乖乖去子午路张记了……
