# -*- mode: org; mode: auto-fill -*-
#+TITLE: 仔句精选, 2018
#+AUTHOR: KDr2

#+OPTIONS: toc:nil
#+OPTIONS: num:nil

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw

#+BEGIN: inc-file :file "gad.inc.org"
#+END:

# - DATE
<2018-02-25 Sun>

# 仔句精选

续[[file:1802-child-unterances-2017.org][仔句精选, 2017]]。

* 20180106
** 旧
   为什么“旧”字这么像 18？
** 名字和实物
   我吃葡萄干（袋子上说叫红玛瑙），顺便给了仔两粒，仔拿着看了看问：“这
   是什么？” 我答“葡萄干。” 仔着急：“你要说它的名字，不要说它本身！它
   叫红玛瑙！”
** 发育
   用自己的小毯子堆一堆，掏个洞，说是隧道，天天趴着看。今天又看隧道，
   说“我是一条消炭色的小蛇，爬到了隧道里，隧道的二层已经发育完成了。”

   “消炭色”我知道是他常看的一套《配色宝典》里面的，但是“发育”这个词不
   知道他从哪里学的，好奇就问了他一下，他说从电视里学的，看来带他看的
   纪录片都没白看，但是这里应该用“建设”吧 :D。

* 20180120

** 完蛋了

   最近看《奇先生妙小姐》跟担心先生学了句“我们完蛋了！”

   玩游戏的时候躲到角落里说：“我被卡住了，爸爸我们完蛋了！” \\
   我懒洋洋地说：“我们没完蛋，我们都有光明的前途…” \\
   仔着急：“我们已经完蛋了！”


** 中国人

   仔妈：今天心情不错，尤其听了好几遍《中意他》。 \\
   仔：什么是《中意他》？ \\
   仔妈：就是白天咱们一家三口一起听的那首歌啊，blahblah… \\
   仔继续：什么是《中意他》？ \\
   仔妈：…… So easy，再给你听一遍你就知道了！ \\
   仔：什么是 “so easy”？ \\
   仔妈：就是“很简单”，英文说法。 \\
   仔：妈妈咱们是中国人啊，你怎么不说中文要说英文啊？ \\
   仔妈：作为一个自干五红裤衩，这被你说的…


** 我要平局，我要看罗马。

   英超早场 BHA vs CHE，我车好不容易一次早早2:0领先，仔过来跟我一起看，
   说： \\
   “怎么是 0-2 呀？我要2-2，我要平局。” \\
   我一脸黑线：“我愿意场上那帮球员也不愿意啊……” \\
   仔：“不行不行…诶，怎么是英超啊怎么不是意甲啊，我要看罗马！” \\
   我：“这轮罗马好像排到周一凌晨了，今天看不了。” \\
   仔：“不行不行…blahblah…” 作势要哭。 \\
   我：“仔，这个赛程是各国足协在赛季前就排好了的，一般不会更改，人家还
   是意甲，你找外交部帮忙估计也不行啊。” \\
   仔嘴一撇，带着哭腔说：“我觉得好残酷。”

* 20180210
** 做到了

   仔玩 Angry Birds — Star Wars II 学了很多星战知识。

   仔：阿纳金最后变成黑武士了，永别了，阿纳金，这是一个悲伤的故事。 \\
   我：对，怪绝地长老会，不让阿纳金复仇，也不让阿纳金谈恋爱。 \\
   仔：但是他最后还是都做到了！ \\
   我：确实，最后娃都生了。 \\
   我对仔妈：咱们这教育对吗？ \\
   仔妈：我也在想… \\

* 20180226
** 巧舌如簧

   又到了选择哄睡人的时候。

   妈妈：今天爸爸哄睡妈妈哄睡？ \\
   仔仔：妈妈。 \\
   妈妈：（得意）是不是因为没人比妈妈更好？ \\
   仔仔：爸爸比妈妈更好，但我就喜欢妈妈这么好的。 \\
   妈妈：呜（小心脏一击必杀） \\

   太会做人了，谁也不得罪 _(:_」∠)_

* 20180320
** 别呜呜了

   周日下午，我感叹：“明天又要上班了，呜呜呜呜呜……” \\
   仔回应：“别呜呜了，再上五天班就又周末了！” \\
   周一下班回家，仔妈跟我说，下午仔正在玩呢，忽然停下说： \\
   “别呜呜了，再上四天班就又周末了。这是要跟爸爸说的。”

** 等差数列

   周一上午睡了午觉，晚上 10 点还不肯睡，我把屋里环境搞的暗暗的，开始
   口头教学活动，成果如下：

   - 知道最大/最小的个位数，两位数，三位数，四位数分别是多少。
   - 知道最大的 N 位数加一后会变成最小的 (N+1) 位数，如 99+1 变 100，
     同理知道当天的最晚时间 23:59:59 秒再过一秒会变成第二天的最早时间。
   - 我给出一个简单的等差数列（首项和公差都是个位数），能答出公差和首
     项分别是什么；知道奇偶序列是公差为 2，首项不同的两个等差数列。

   最后通过口头考试后，满意地去睡觉了。

#+BEGIN: inc-file :file "gad.inc.org"
#+END:

* Discuss and Comment
  #+BEGIN: inc-file :file "comment.inc.org"
  #+END:
