# -*- mode: org; mode: auto-fill; -*-
#+TITLE: About me and this site
#+AUTHOR: KDr2

#+BEGIN: inc-file :file "common.inc.org"
#+END:
#+CALL: dynamic-header() :results raw
#+CALL: meta-keywords(kws='("KDr2" "free lancer")) :results raw

* About Me

  - Emacs 用户，Linux 用户，支持 Open Source, 不反 GNU, 不反 GPL。
  - 喜钻研技术，驳杂却乐在其中。
  - 曾爱阅读，正试旧爱重习。
  - 向往写作，无奈笔力孱弱。
  - 五音不全，全然不通音律。
  - 肯于分享，力图不为人师。
  - 追求完美，偶致束手束足。
  - 意在修身，然却心有旁鶩。

** Work

   I am a software developer/computer programmer, and now working
   remotely as a freelance developer/consultant.

** Contact
   :PROPERTIES:
   :CUSTOM_ID: contact_me
   :END:
   - Location: XI'AN, SHANNXI, China
   - Skype : zhuoql
   - Email : zhuo<at>bitoasis.com
   - Mobile : +86 0b10111010 05532 0x0636
   - [[file:schedule.org][My Schedule]]
#   - skype : [[data:text/plain;base64,emh1b3Fs]]
#   - Email : [[data:text/plain;base64,a2lsbHkuZHJhd0BnbWFpbC5jb20=]]


#+BEGIN: inc-file :file "gad.inc.org"
#+END

* About This Site
** Content of the site
   I write about myself on this site, and write only for myself, not
   for any other readers.

** Technical Persective
  This site is built with emacs and org-mode, and some other tools, I
  list all of them here:

  - Emacs: http://www.gnu.org/software/emacs/
  - Org-Mode: http://orgmode.org/
  - Disqus: http://disqus.com/
  - Google Analytics: http://www.google.com/analytics/

  You can find my org mode configuration at
  https://github.com/KDr2/emacs.d/blob/master/src/elisp/tools/init-org.el
  and https://github.com/KDr2/kdr2-on-web/blob/master/script/.
  The source repository of this site is at https://github.com/KDr2/kdr2-on-web.

* Support Me
  :PROPERTIES:
  :CUSTOM_ID: support_me
  :END:
  - 
    #+BEGIN_HTML
    <form id="paypal" name="_xclick" action="https://www.paypal.com/cgi-bin/webscr" method="post">
    <input type="hidden" name="cmd" value="_xclick">
    <input type="hidden" name="business" value="zhuo@bitoasis.com">
    <input type="hidden" name="item_name" value="Support KDr2.com">
    <input type="hidden" name="item_number" value="1">
    <input type="hidden" name="lc" value="US">
    <input type="hidden" name="currency_code" value="USD">
    <input type="hidden" name="tax" value="0">
    <input type="hidden" name="return" value="http://kdr2.com">
    <button alt="Support KDr2" class="button_to_link"
    data-ga-id="donate-link" data-ga-label="ABOUT" data-ga-action="link.paypal.click">
    Support KDr2 by Paypal
    </button>
    </form>
    #+END_HTML
  - 
    #+ATTR_HTML: :target _blank :class gat-click :data-ga-id donate-link :data-ga-action link.alipay.click :data-ga-label ABOUT
    [[https://me.alipay.com/KDr2][通过支付宝]]

  #+BEGIN: inc-file :file "gad.inc.org"
  #+END

* Discuss and Comment
#+INCLUDE: ../include/disqus.inc.org
